export const tickets = [
  {
    "_index": "ticket",
    "_type": "ticket",
    "_id": "TZLAY2QBWnTf1p1xerPA",
    "_score": 0.2876821,
    "_source": {
      "status": "Open",
      "service_restored_date": "1/0/1900 0:00",
      "sla_status": "74",
      "tag::eventtype": "",
      "request_completion_date": "1/0/1900 0:00",
      "resolved_financial_year": "",
      "date_zone": "0",
      "Application": "EBPP",
      "severity_number": "4",
      "app_family_mots": "ODM Support",
      "date_minute": "50",
      "cause_code": "",
      "owner": "sd_surenthranmar",
      "problem_abstract": "unable to view details",
      "problem_type": "Account",
      "ticket_source": "EBPP",
      "auto_sub_cat3": "",
      "asset_id": "EBPP",
      "action_code": "",
      "reported_year": "",
      "current_ticket_state": "Open",
      "severity": "4",
      "source": "/opt/splunk/etc/apps/aiam-itsm-ticketanalysis-data-clients-new/data/uploads/test/itsm_Automation_Architect_ML_Cat_ticket_Data.csv",
      "reported_month": "",
      "eventtype": "",
      "problem_mapping": "Account",
      "splunk_server": "ip-10-0-0-164",
      "Legacy_Owner": "ODM Support",
      "linecount": "1",
      "natnumber": "",
      "date_year": "2016",
      "tag": "",
      "date_hour": "20",
      "work_queue": "ODM EBPP",
      "product": "EBPP",
      "owner_name": "sd_surenthranmar",
      "resolved_year": "",
      "index": "aiam_itsm_ticket_ptest_ctest_index",
      "CC": "",
      "date_wday": "tuesday",
      "workfolder": "Open Dispatch",
      "ticket_number": "1606141762",
      "resolved_month": "",
      "splunk_auto_category": "Application",
      "punct": ",,_,_,,,,,,,,,,,,//_:,//_:,//_:,//_:,//_:,,,,,_,_,",
      "host": "ip-10-0-0-164",
      "Portfolio": "ODM Support",
      "reported_month_year": "",
      "action_code_category": "",
      "reported_financial_year": "",
      "Portfolio_ID": "74",
      "splunk_server_group": "",
      "cause_code_category": "",
      "sourcetype": "aiam_itsm_ticket_ptest_ctest",
      "incident_id": "1606141762",
      "last_resolved_date_time": "1/0/1900 0:00",
      "system_user": "ODM Support",
      "date_month": "june",
      "natnumbersv": "",
      "time_submitted": "6/14/2016 20:50",
      "SPEECH_ERROR": "",
      "queue": "ODM EBPP",
      "_time": "2016-06-14T20:50:00.000+0000",
      "resolved_month_year": "",
      "date_mday": "14",
      "Application_Status": "Active",
      "last_accepted_date_time": "",
      "_raw": "1606141762,1606141762,ODM Support,ODM Support,74,EBPP,EBPP,EBPP,Active,,,,EBPP,Open,Open,6/14/2016 20:50,6/14/2016 20:50,1/0/1900 0:00,1/0/1900 0:00,1/0/1900 0:00,,,sd_surenthranmar,sd_surenthranmar,ODM EBPP,ODM EBPP,Open Dispatch,unable to view details,unable to view details,Account,Account,4,4,ODM Support,ODM Support,74,,,Application,GUI Issues",
      "ticket_closed_date": "",
      "date_created": "6/14/2016 20:50",
      "splunk_auto_sub_category": "GUI Issues",
      "natnumbersb": ""
    }
  },
  {
    "_index": "ticket",
    "_type": "ticket",
    "_id": "TZLAY2QBWnTf1p1xerPA",
    "_score": 0.2876821,
    "_source": {
      "status": "Open",
      "service_restored_date": "1/0/1900 0:00",
      "sla_status": "74",
      "tag::eventtype": "",
      "request_completion_date": "1/0/1900 0:00",
      "resolved_financial_year": "",
      "date_zone": "0",
      "Application": "EBPP",
      "severity_number": "4",
      "app_family_mots": "ODM Support",
      "date_minute": "50",
      "cause_code": "",
      "owner": "sd_surenthranmar",
      "problem_abstract": "unable to view details",
      "problem_type": "Account",
      "ticket_source": "EBPP",
      "auto_sub_cat3": "",
      "asset_id": "EBPP",
      "action_code": "",
      "reported_year": "",
      "current_ticket_state": "Open",
      "severity": "4",
      "source": "/opt/splunk/etc/apps/aiam-itsm-ticketanalysis-data-clients-new/data/uploads/test/itsm_Automation_Architect_ML_Cat_ticket_Data.csv",
      "reported_month": "",
      "eventtype": "",
      "problem_mapping": "Account",
      "splunk_server": "ip-10-0-0-164",
      "Legacy_Owner": "ODM Support",
      "linecount": "1",
      "natnumber": "",
      "date_year": "2016",
      "tag": "",
      "date_hour": "20",
      "work_queue": "ODM EBPP",
      "product": "EBPP",
      "owner_name": "sd_surenthranmar",
      "resolved_year": "",
      "index": "aiam_itsm_ticket_ptest_ctest_index",
      "CC": "",
      "date_wday": "tuesday",
      "workfolder": "Open Dispatch",
      "ticket_number": "1606141762",
      "resolved_month": "",
      "splunk_auto_category": "Application",
      "punct": ",,_,_,,,,,,,,,,,,//_:,//_:,//_:,//_:,//_:,,,,,_,_,",
      "host": "ip-10-0-0-164",
      "Portfolio": "ODM Support",
      "reported_month_year": "",
      "action_code_category": "",
      "reported_financial_year": "",
      "Portfolio_ID": "74",
      "splunk_server_group": "",
      "cause_code_category": "",
      "sourcetype": "aiam_itsm_ticket_ptest_ctest",
      "incident_id": "1606141762",
      "last_resolved_date_time": "1/0/1900 0:00",
      "system_user": "ODM Support",
      "date_month": "june",
      "natnumbersv": "",
      "time_submitted": "6/14/2016 20:50",
      "SPEECH_ERROR": "",
      "queue": "ODM EBPP",
      "_time": "2016-06-14T20:50:00.000+0000",
      "resolved_month_year": "",
      "date_mday": "14",
      "Application_Status": "Active",
      "last_accepted_date_time": "",
      "_raw": "1606141762,1606141762,ODM Support,ODM Support,74,EBPP,EBPP,EBPP,Active,,,,EBPP,Open,Open,6/14/2016 20:50,6/14/2016 20:50,1/0/1900 0:00,1/0/1900 0:00,1/0/1900 0:00,,,sd_surenthranmar,sd_surenthranmar,ODM EBPP,ODM EBPP,Open Dispatch,unable to view details,unable to view details,Account,Account,4,4,ODM Support,ODM Support,74,,,Application,GUI Issues",
      "ticket_closed_date": "",
      "date_created": "6/14/2016 20:50",
      "splunk_auto_sub_category": "GUI Issues",
      "natnumbersb": ""
    }
  },
  {
    "_index": "ticket",
    "_type": "ticket",
    "_id": "TZLAY2QBWnTf1p1xerPA",
    "_score": 0.2876821,
    "_source": {
      "status": "Open",
      "service_restored_date": "1/0/1900 0:00",
      "sla_status": "74",
      "tag::eventtype": "",
      "request_completion_date": "1/0/1900 0:00",
      "resolved_financial_year": "",
      "date_zone": "0",
      "Application": "EBPP",
      "severity_number": "4",
      "app_family_mots": "ODM Support",
      "date_minute": "50",
      "cause_code": "",
      "owner": "sd_surenthranmar",
      "problem_abstract": "unable to view details",
      "problem_type": "Account",
      "ticket_source": "EBPP",
      "auto_sub_cat3": "",
      "asset_id": "EBPP",
      "action_code": "",
      "reported_year": "",
      "current_ticket_state": "Open",
      "severity": "4",
      "source": "/opt/splunk/etc/apps/aiam-itsm-ticketanalysis-data-clients-new/data/uploads/test/itsm_Automation_Architect_ML_Cat_ticket_Data.csv",
      "reported_month": "",
      "eventtype": "",
      "problem_mapping": "Account",
      "splunk_server": "ip-10-0-0-164",
      "Legacy_Owner": "ODM Support",
      "linecount": "1",
      "natnumber": "",
      "date_year": "2016",
      "tag": "",
      "date_hour": "20",
      "work_queue": "ODM EBPP",
      "product": "EBPP",
      "owner_name": "sd_surenthranmar",
      "resolved_year": "",
      "index": "aiam_itsm_ticket_ptest_ctest_index",
      "CC": "",
      "date_wday": "tuesday",
      "workfolder": "Open Dispatch",
      "ticket_number": "1606141762",
      "resolved_month": "",
      "splunk_auto_category": "Application",
      "punct": ",,_,_,,,,,,,,,,,,//_:,//_:,//_:,//_:,//_:,,,,,_,_,",
      "host": "ip-10-0-0-164",
      "Portfolio": "ODM Support",
      "reported_month_year": "",
      "action_code_category": "",
      "reported_financial_year": "",
      "Portfolio_ID": "74",
      "splunk_server_group": "",
      "cause_code_category": "",
      "sourcetype": "aiam_itsm_ticket_ptest_ctest",
      "incident_id": "1606141762",
      "last_resolved_date_time": "1/0/1900 0:00",
      "system_user": "ODM Support",
      "date_month": "june",
      "natnumbersv": "",
      "time_submitted": "6/14/2016 20:50",
      "SPEECH_ERROR": "",
      "queue": "ODM EBPP",
      "_time": "2016-06-14T20:50:00.000+0000",
      "resolved_month_year": "",
      "date_mday": "14",
      "Application_Status": "Active",
      "last_accepted_date_time": "",
      "_raw": "1606141762,1606141762,ODM Support,ODM Support,74,EBPP,EBPP,EBPP,Active,,,,EBPP,Open,Open,6/14/2016 20:50,6/14/2016 20:50,1/0/1900 0:00,1/0/1900 0:00,1/0/1900 0:00,,,sd_surenthranmar,sd_surenthranmar,ODM EBPP,ODM EBPP,Open Dispatch,unable to view details,unable to view details,Account,Account,4,4,ODM Support,ODM Support,74,,,Application,GUI Issues",
      "ticket_closed_date": "",
      "date_created": "6/14/2016 20:50",
      "splunk_auto_sub_category": "GUI Issues",
      "natnumbersb": ""
    }
  },
  {
    "_index": "ticket",
    "_type": "ticket",
    "_id": "TZLAY2QBWnTf1p1xerPA",
    "_score": 0.2876821,
    "_source": {
      "status": "Open",
      "service_restored_date": "1/0/1900 0:00",
      "sla_status": "74",
      "tag::eventtype": "",
      "request_completion_date": "1/0/1900 0:00",
      "resolved_financial_year": "",
      "date_zone": "0",
      "Application": "EBPP",
      "severity_number": "4",
      "app_family_mots": "ODM Support",
      "date_minute": "50",
      "cause_code": "",
      "owner": "sd_surenthranmar",
      "problem_abstract": "unable to view details",
      "problem_type": "Account",
      "ticket_source": "EBPP",
      "auto_sub_cat3": "",
      "asset_id": "EBPP",
      "action_code": "",
      "reported_year": "",
      "current_ticket_state": "Open",
      "severity": "4",
      "source": "/opt/splunk/etc/apps/aiam-itsm-ticketanalysis-data-clients-new/data/uploads/test/itsm_Automation_Architect_ML_Cat_ticket_Data.csv",
      "reported_month": "",
      "eventtype": "",
      "problem_mapping": "Account",
      "splunk_server": "ip-10-0-0-164",
      "Legacy_Owner": "ODM Support",
      "linecount": "1",
      "natnumber": "",
      "date_year": "2016",
      "tag": "",
      "date_hour": "20",
      "work_queue": "ODM EBPP",
      "product": "EBPP",
      "owner_name": "sd_surenthranmar",
      "resolved_year": "",
      "index": "aiam_itsm_ticket_ptest_ctest_index",
      "CC": "",
      "date_wday": "tuesday",
      "workfolder": "Open Dispatch",
      "ticket_number": "1606141762",
      "resolved_month": "",
      "splunk_auto_category": "Application",
      "punct": ",,_,_,,,,,,,,,,,,//_:,//_:,//_:,//_:,//_:,,,,,_,_,",
      "host": "ip-10-0-0-164",
      "Portfolio": "ODM Support",
      "reported_month_year": "",
      "action_code_category": "",
      "reported_financial_year": "",
      "Portfolio_ID": "74",
      "splunk_server_group": "",
      "cause_code_category": "",
      "sourcetype": "aiam_itsm_ticket_ptest_ctest",
      "incident_id": "1606141762",
      "last_resolved_date_time": "1/0/1900 0:00",
      "system_user": "ODM Support",
      "date_month": "june",
      "natnumbersv": "",
      "time_submitted": "6/14/2016 20:50",
      "SPEECH_ERROR": "",
      "queue": "ODM EBPP",
      "_time": "2016-06-14T20:50:00.000+0000",
      "resolved_month_year": "",
      "date_mday": "14",
      "Application_Status": "Active",
      "last_accepted_date_time": "",
      "_raw": "1606141762,1606141762,ODM Support,ODM Support,74,EBPP,EBPP,EBPP,Active,,,,EBPP,Open,Open,6/14/2016 20:50,6/14/2016 20:50,1/0/1900 0:00,1/0/1900 0:00,1/0/1900 0:00,,,sd_surenthranmar,sd_surenthranmar,ODM EBPP,ODM EBPP,Open Dispatch,unable to view details,unable to view details,Account,Account,4,4,ODM Support,ODM Support,74,,,Application,GUI Issues",
      "ticket_closed_date": "",
      "date_created": "6/14/2016 20:50",
      "splunk_auto_sub_category": "GUI Issues",
      "natnumbersb": ""
    }
  },
  {
    "_index": "ticket",
    "_type": "ticket",
    "_id": "TZLAY2QBWnTf1p1xerPA",
    "_score": 0.2876821,
    "_source": {
      "status": "Open",
      "service_restored_date": "1/0/1900 0:00",
      "sla_status": "74",
      "tag::eventtype": "",
      "request_completion_date": "1/0/1900 0:00",
      "resolved_financial_year": "",
      "date_zone": "0",
      "Application": "EBPP",
      "severity_number": "4",
      "app_family_mots": "ODM Support",
      "date_minute": "50",
      "cause_code": "",
      "owner": "sd_surenthranmar",
      "problem_abstract": "unable to view details",
      "problem_type": "Account",
      "ticket_source": "EBPP",
      "auto_sub_cat3": "",
      "asset_id": "EBPP",
      "action_code": "",
      "reported_year": "",
      "current_ticket_state": "Open",
      "severity": "4",
      "source": "/opt/splunk/etc/apps/aiam-itsm-ticketanalysis-data-clients-new/data/uploads/test/itsm_Automation_Architect_ML_Cat_ticket_Data.csv",
      "reported_month": "",
      "eventtype": "",
      "problem_mapping": "Account",
      "splunk_server": "ip-10-0-0-164",
      "Legacy_Owner": "ODM Support",
      "linecount": "1",
      "natnumber": "",
      "date_year": "2016",
      "tag": "",
      "date_hour": "20",
      "work_queue": "ODM EBPP",
      "product": "EBPP",
      "owner_name": "sd_surenthranmar",
      "resolved_year": "",
      "index": "aiam_itsm_ticket_ptest_ctest_index",
      "CC": "",
      "date_wday": "tuesday",
      "workfolder": "Open Dispatch",
      "ticket_number": "1606141762",
      "resolved_month": "",
      "splunk_auto_category": "Application",
      "punct": ",,_,_,,,,,,,,,,,,//_:,//_:,//_:,//_:,//_:,,,,,_,_,",
      "host": "ip-10-0-0-164",
      "Portfolio": "ODM Support",
      "reported_month_year": "",
      "action_code_category": "",
      "reported_financial_year": "",
      "Portfolio_ID": "74",
      "splunk_server_group": "",
      "cause_code_category": "",
      "sourcetype": "aiam_itsm_ticket_ptest_ctest",
      "incident_id": "1606141762",
      "last_resolved_date_time": "1/0/1900 0:00",
      "system_user": "ODM Support",
      "date_month": "june",
      "natnumbersv": "",
      "time_submitted": "6/14/2016 20:50",
      "SPEECH_ERROR": "",
      "queue": "ODM EBPP",
      "_time": "2016-06-14T20:50:00.000+0000",
      "resolved_month_year": "",
      "date_mday": "14",
      "Application_Status": "Active",
      "last_accepted_date_time": "",
      "_raw": "1606141762,1606141762,ODM Support,ODM Support,74,EBPP,EBPP,EBPP,Active,,,,EBPP,Open,Open,6/14/2016 20:50,6/14/2016 20:50,1/0/1900 0:00,1/0/1900 0:00,1/0/1900 0:00,,,sd_surenthranmar,sd_surenthranmar,ODM EBPP,ODM EBPP,Open Dispatch,unable to view details,unable to view details,Account,Account,4,4,ODM Support,ODM Support,74,,,Application,GUI Issues",
      "ticket_closed_date": "",
      "date_created": "6/14/2016 20:50",
      "splunk_auto_sub_category": "GUI Issues",
      "natnumbersb": ""
    }
  },
  {
    "_index": "ticket",
    "_type": "ticket",
    "_id": "TZLAY2QBWnTf1p1xerPA",
    "_score": 0.2876821,
    "_source": {
      "status": "Open",
      "service_restored_date": "1/0/1900 0:00",
      "sla_status": "74",
      "tag::eventtype": "",
      "request_completion_date": "1/0/1900 0:00",
      "resolved_financial_year": "",
      "date_zone": "0",
      "Application": "EBPP",
      "severity_number": "4",
      "app_family_mots": "ODM Support",
      "date_minute": "50",
      "cause_code": "",
      "owner": "sd_surenthranmar",
      "problem_abstract": "unable to view details",
      "problem_type": "Account",
      "ticket_source": "EBPP",
      "auto_sub_cat3": "",
      "asset_id": "EBPP",
      "action_code": "",
      "reported_year": "",
      "current_ticket_state": "Open",
      "severity": "4",
      "source": "/opt/splunk/etc/apps/aiam-itsm-ticketanalysis-data-clients-new/data/uploads/test/itsm_Automation_Architect_ML_Cat_ticket_Data.csv",
      "reported_month": "",
      "eventtype": "",
      "problem_mapping": "Account",
      "splunk_server": "ip-10-0-0-164",
      "Legacy_Owner": "ODM Support",
      "linecount": "1",
      "natnumber": "",
      "date_year": "2016",
      "tag": "",
      "date_hour": "20",
      "work_queue": "ODM EBPP",
      "product": "EBPP",
      "owner_name": "sd_surenthranmar",
      "resolved_year": "",
      "index": "aiam_itsm_ticket_ptest_ctest_index",
      "CC": "",
      "date_wday": "tuesday",
      "workfolder": "Open Dispatch",
      "ticket_number": "1606141762",
      "resolved_month": "",
      "splunk_auto_category": "Application",
      "punct": ",,_,_,,,,,,,,,,,,//_:,//_:,//_:,//_:,//_:,,,,,_,_,",
      "host": "ip-10-0-0-164",
      "Portfolio": "ODM Support",
      "reported_month_year": "",
      "action_code_category": "",
      "reported_financial_year": "",
      "Portfolio_ID": "74",
      "splunk_server_group": "",
      "cause_code_category": "",
      "sourcetype": "aiam_itsm_ticket_ptest_ctest",
      "incident_id": "1606141762",
      "last_resolved_date_time": "1/0/1900 0:00",
      "system_user": "ODM Support",
      "date_month": "june",
      "natnumbersv": "",
      "time_submitted": "6/14/2016 20:50",
      "SPEECH_ERROR": "",
      "queue": "ODM EBPP",
      "_time": "2016-06-14T20:50:00.000+0000",
      "resolved_month_year": "",
      "date_mday": "14",
      "Application_Status": "Active",
      "last_accepted_date_time": "",
      "_raw": "1606141762,1606141762,ODM Support,ODM Support,74,EBPP,EBPP,EBPP,Active,,,,EBPP,Open,Open,6/14/2016 20:50,6/14/2016 20:50,1/0/1900 0:00,1/0/1900 0:00,1/0/1900 0:00,,,sd_surenthranmar,sd_surenthranmar,ODM EBPP,ODM EBPP,Open Dispatch,unable to view details,unable to view details,Account,Account,4,4,ODM Support,ODM Support,74,,,Application,GUI Issues",
      "ticket_closed_date": "",
      "date_created": "6/14/2016 20:50",
      "splunk_auto_sub_category": "GUI Issues",
      "natnumbersb": ""
    }
  }
]